FROM golang:latest

WORKDIR /app

# Copy go.mod and go.sum to the working directory
COPY ../../backend/go.mod ../../backend/go.sum ./

# Download and verify the dependencies
RUN go mod download && go mod verify

# Copy the backend directory contents to the working directory
COPY ../../backend/ /app

# Build the Go application
RUN go build -v -o main main.go

# Command to run the Go application
CMD ["/app/main"]


