name: "greybox-api"

services:
  api:
    build:
      context: .
      dockerfile: docker/api/dockerfile
   
    env_file:
      - ./backend/.env
    container_name: boa-backend
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    

  nginx: 
    restart: always
    container_name: nginx
    build:
        context: .
        dockerfile: ./docker/nginx/dockerfile
    ports:
        - 80:80
        - 443:443
    volumes:
        
        - ./docker/nginx/development:/etc/nginx/conf.d              
    depends_on: 
        - api

    command: ["nginx", "-g", "daemon off;"]


volumes:
  api_volume: