version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/dockerfile
    env_file:
      - ./backend/.env
    container_name: api
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - api_volume:/usr/src/app/  # This maps the backend source code to the container
      - sqlite_db:/usr/src/app/test.db
    
  nginx: 
    restart: always
    container_name: nginx-server
    build:
      context: .
      dockerfile: ./docker/nginx/dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on: 
      - api
    command: ["nginx", "-g", "daemon off;"]
    
    
volumes:
  sqlite_db:
  api_volume: