version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/dockerfile
    env_file:
      - ./backend/.env
    container_name: api
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./backend:/app  # This maps the backend source code to the container
      - sqlite_db:/app/test.db
    
  nginx: 
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on: 
      - api
      - certbot
    command: ["nginx", "-g", "daemon off;"]

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/nginx/certs:/etc/letsencrypt
      - ./docker/nginx/development:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
    
volumes:
  sqlite_db: