FROM nginx

# Remove the default nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf


# Expose port 80 to allow outside access
EXPOSE 80

# Command to start nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]